// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhzegojcirvzzfhuybtg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoemVnb2pjaXJ2enpmaHV5YnRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNDAyNDQsImV4cCI6MjA2MjgxNjI0NH0.69OIz43JgCbufQACdx4pbjSQgEQS69m2kRjlbHEyoYQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);